languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "æ¼©æ¶¡ğŸŒ€"
#logo = "img/avatar.png"
description = "æ¼©æ¶¡ğŸŒ€"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "æˆ‘çš„åå­—å«æµ©ä»”"
  image = "img/avatar.png"
  headline = "çº¸ä¸Šå¾—æ¥ç»ˆè§‰æµ…ï¼Œç»çŸ¥æ­¤äº‹è¦èº¬è¡Œ"
  bio = "A little bit about you"
  links = [
     { link = "http://cuihao.fun" },
     { github = "https://github.com/itcuihao" },
     { twitter = "https://twitter.com/itcuihao" },
     { bars = "http://blog.cuihao.fun" },
     { edit = "http://memos.cuihao.fun" },
  ]